# Generated by Django 5.1 on 2024-08-12 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseva_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='repository',
            name='files',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='loc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='dseva_content.developer'),
        ),
        migrations.AddField(
            model_name='repository',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='dseva_content.repository'),
        ),
        migrations.AddField(
            model_name='repository',
            name='stars_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='watched_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repository',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
