# Generated by Django 5.1 on 2024-08-12 12:35

import django.utils.timezone
import dseva_content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseva_content', '0003_repository_created_at_repository_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='repository',
            name='updated_at',
            field=dseva_content.models.repository.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
