# Generated by Django 5.1 on 2024-10-24 10:12

import django.utils.timezone
import dseva_content.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dseva_content', '0005_alter_repository_description_alter_repository_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=dseva_content.models.repository.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
