# Generated by Django 5.1 on 2024-10-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseva_content', '0006_alter_repository_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='foreign_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
