# Generated by Django 5.1 on 2024-10-24 14:34

import django.utils.timezone
import dseva_content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseva_content', '0007_repository_foreign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='firstVisit',
            field=dseva_content.models.repository.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='repository',
            name='lastVisit',
            field=dseva_content.models.repository.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='repository',
            name='type',
            field=models.CharField(default='Repository', editable=False, max_length=255),
        ),
    ]
