# Generated by Django 5.1 on 2024-12-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseva_content', '0008_repository_firstvisit_repository_lastvisit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='foreign_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
