# Generated by Django 5.1 on 2025-01-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseva_content', '0009_alter_repository_foreign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
