# Generated by Django 5.1 on 2025-01-30 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseva_content', '0010_repository_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='dseva_content.developer'),
        ),
    ]
