# Generated by Django 5.1 on 2025-01-30 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseva_content', '0001_squashed_0011_developer_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='owner',
            new_name='ownerD',
        ),
        migrations.AddField(
            model_name='developer',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='dseva_content.repository'),
        ),
    ]
