# Generated by Django 5.1 on 2025-02-12 18:55

import django.utils.timezone
import dseva_content.models.developer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseva_content', '0013_developer_foreign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='created_at',
            field=dseva_content.models.developer.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='firstVisit',
            field=dseva_content.models.developer.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='lastVisit',
            field=dseva_content.models.developer.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='updated_at',
            field=dseva_content.models.developer.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
