# Generated by Django 5.1 on 2025-02-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseva_content', '0014_developer_created_at_developer_firstvisit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='type',
            field=models.CharField(default='Developer', editable=False, max_length=255),
        ),
    ]
