services:
  web:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/usr/src/dseva_backend
    ports:
      - 8000:8000
      - 3000:3000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=dsevadb
  collector:
    build: ./collector
    #command: python collector.py
    volumes:
      - ./collector:/usr/src/collector
    ports:
      - 3001:3001
    env_file:
      - ./.env_full.dev
    depends_on:
      - web
volumes:
  postgres_data: